OCPB-26. Enhanced slack notifier

diff --git a/.github/workflows/playwright.yml b/.github/workflows/playwright.yml
--- a/.github/workflows/playwright.yml
+++ b/.github/workflows/playwright.yml
@@ -69,16 +69,38 @@ jobs:
       with:
         report-path: 'frontend/playwright-report/*.json'
       if: always()
-    - name: Notify Slack
-      if: always()
-      env:
-        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
-      run: |
-        STATUS="Success"
-        if [ "${{ job.status }}" != "success" ]; then
-          STATUS="@channel Failure"
-        fi
-        curl -X POST \
-           -H 'Content-type: application/json' \
-           --data "{\"text\":\"Nightly Playwright Tests: $STATUS\"}" \
-           $SLACK_WEBHOOK   
+  slack-notifier:
+    runs-on: ubuntu-latest
+    if: ${{ !cancelled() }}
+    permissions:
+      actions: read
+      contents: read
+    needs: e2e-nightly-test
+    steps:
+      - name: Get failure info
+        id: failure-info
+        run: |
+          delimiter=$(openssl rand -hex 8)
+          {
+            echo "ERRORS_OUTPUT<<$delimiter"
+            curl -v -L \
+              -H "Accept: application/vnd.github+json" \
+              -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
+              -H "X-GitHub-Api-Version: 2022-11-28" \
+              https://api.github.com/repos/${{ github.repository }}/actions/jobs/${{ needs.e2e-nightly-test.outputs.job-id }}/logs \
+              | (grep '✖' || echo "No errors found") | sed "s,\x1B\[[0-9;]*[a-zA-Z],,g"
+            echo -e "\n$delimiter\n"
+          } | tee -a "$GITHUB_OUTPUT"
+#      - name: Notify Slack
+#      if: always()
+#      env:
+#        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
+#      run: |
+#        STATUS="Success"
+#        if [ "${{ job.status }}" != "success" ]; then
+#          STATUS="@channel Failure"
+#        fi
+#        curl -X POST \
+#           -H 'Content-type: application/json' \
+#           --data "{\"text\":\"Nightly Playwright Tests: $STATUS\"}" \
+#           $SLACK_WEBHOOK   
